sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t shlomiatzmon/docker-compose -f Dockerfile.dev .

script:
  - docker run -e CI=true shlomiatzmon/docker-compose npm run test